### ISSUE TITLE
FBilling on FreePBX 13.0.70/Asterisk 13.7.2 Breaks Extensions management

### ISSUE THREAD

**Issue by blazestudios97** [alkali147/fbilling#29]
Installed FBilling on a fresh install of FreePBX 13 with Asterisk 13 and after the install any attempt to add a new extension or edit an existing extensions results in this error:

```
/var/www/html/admin/modules/fbilling/functions.inc.php 
34. 
35.global $db;
36. 
37.## since provided gui_link opens in current window/tab we have to do this so some of our links will be open in new tab
38.class gui_link_new_tab extends guitext {
39.    function gui_link_new_tab($elemname, $text, $url, $userlang = true) {
40.        $parent_class = get_parent_class($this);
41.        parent::$parent_class($elemname, $text);
42.        $this->html_text = "<a href=\"$url\" target=\"_blank\" id =\"$this->elemname\">$text</a>";
43.    }

```

This basically makes FBilling unusable. Has it been tested with these latest releases?

**Comment by alkali147** [comment]
Hello,

Although FreePBX 13 is not "officially" supported and tested (in terms of GUI), it works -
commenting out line 41 on `/var/www/html/admin/modules/fbilling/functions.inc.php` - solves the issue

`//parent::$parent_class($elemname, $text);`

hope that helps...

**Comment by blazestudios97** [comment]
Regardless of this, there is also issue #30 that is making it impossible to use FBilling.

**Comment by blazestudios97** [comment]
Commenting line 41 fixed the extension issue but still can't use FBilling due to issue #30
