### ISSUE TITLE
FBilling Administration CSS Impacts Layout

### ISSUE THREAD

**Issue by blazestudios97** [alkali147/fbilling#30]
With FBilling Administration the CSS makes the interface unusable because it makes the page footer cover almost 75% of the page. When you click on options such as "Tenants" or any option that doesn't have a form fields already and just a "Add" button the page loads but then the Footer jumps and covers up the area making the "Add" button no longer visible or usable.

[http://picpaste.com/CaptureWiz_002-TQmj79nC.gif](url) Here's an animated GIF of me navigating through the interface. I tried Chrome, Firefox and Internet Explorer all with the same issue

**Comment by alkali147** [comment]
Recent commits should fix the issue - worked on latest FreePBX version on my test box, please report back, Thanks!

**Comment by blazestudios97** [comment]
This fixed the CSS layout issues.
