### ISSUE TITLE
FreePBX 13 - Error when adding Permissions in FBilling Admin

### ISSUE THREAD

**Issue by blazestudios97** [alkali147/fbilling#31]
Click on "Add" in the Permissions section of the FBilling Admin and it results in the following error:

`/var/www/html/admin/modules/fbilling/components/permissions.php
                <td>
                    <a href='#' class='info'><?php echo _("Weights"); ?><span><?php echo _("Select weights that will belong to this permissions.<br />Extensions assigned to this permission will be able to dial prefixes with weights selected here") ?></span>
                </td>
                <td>
                    <select multiple name='weight_id[]' tabindex="<?php echo ++$tabindex;?>">
                        <?php
                            foreach ($weight_list as $weight) {
                                if (in_array($weight['id'], $selected_weights)) {
                                    echo "<option selected value=$weight[id]>$weight[name]</option>";
                                } else {
`

**Comment by blazestudios97** [comment]
Additional details:

Whoops \ Exception \ ErrorException (E_WARNING)
in_array() expects parameter 2 to be array, null given

**Comment by alkali147** [comment]
Do you have latest source? because that issue probably fixed in this commit 6f76ac7797d187f10c7ca79b32ec7287c630da07
Thanks!

**Comment by blazestudios97** [comment]
I pulled the 1.0 full release source last night. I will adjust that fix.

**Comment by alkali147** [comment]
Yeah, I found that issue just now when fixing CSS related issues. You can pull latest master tree, and it should be fixed. I'll draft the release later today.

**Comment by blazestudios97** [comment]
Yes, that fixed the issue.
